apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: telemeter-reporter-cronjob-daily
  namespace: sd-sre
  resourceVersion: "70664704"
  selfLink: /apis/batch/v1beta1/namespaces/sd-sre/cronjobs/telemeter-reporter-cronjob-daily
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - sh
            - -c
            - telemeter-reporter --log info --format html --format csv --parents --minify
              /telemeter-reporter-storage/reports/$(date +"%Y-%m/%F.28dSLOReport")
            env:
            - name: TELEMETER_TOKEN
              valueFrom:
                secretKeyRef:
                  key: telemeterToken
                  name: telemeter-reporter-secret
            - name: UHC_TOKEN
              valueFrom:
                secretKeyRef:
                  key: uhcToken
                  name: telemeter-reporter-secret
            - name: TELEMETER_REPORTER_CONFIG
              value: /telemeter-reporter-config/reporter_conf.yml
            - name: TELEMETER_SSL_CA
              value: /telemeter-reporter-config/RHCertBundle.pem
            image: docker-registry.default.svc:5000/sd-sre/telemeter-reporter
            imagePullPolicy: Always
            name: telemeter-reporter-daily
            resources:
              limits:
                cpu: 500m
                memory: 300Mi
              requests:
                cpu: 250m
                memory: 250Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /telemeter-reporter-config
              name: config-volume
            - mountPath: /telemeter-reporter-storage
              name: telemeter-reporter-storage
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: telemeter-reporter-config
            name: config-volume
          - name: telemeter-reporter-storage
            persistentVolumeClaim:
              claimName: telemeter-reporter-storage-claim
  schedule: 0 5 * * *
  successfulJobsHistoryLimit: 3
  suspend: false

