apiVersion: v1
data:
  telemeterToken: >-
    <Enter Your Token>
  uhcToken: >-
    <Enter Your Token>
kind: Secret
metadata:
  name: telemeter-reporter-secret
  namespace: sd-sre
  resourceVersion: '60625761'
  selfLink: /api/v1/namespaces/telemeter-reporter/secrets/telemeter-reporter-secret
type: Opaque