apiVersion: v1
data:
  WebHookSecretKey: <Add Secret>
kind: Secret
metadata:
  name: telemeter-reporter-webhook-secret
  namespace: sd-sre
  resourceVersion: '61501051'
  selfLink: >-
    /api/v1/namespaces/sd-sre/secrets/telemeter-reporter-webhook-secret
type: Opaque

